TARGET=crc_encoder_20190388
SOURCE = crc_encoder_20190388.cc
# crc_decoder_20190388: crc_decoder_20190388.cc
# 	g++ -o crc_decoder_20190388 crc_decoder_20190388.cc

# clean:
# 	rm -rf *~ crc_decoder_20190388

${TARGET}: ${SOURCE}
	g++ -o ${TARGET} ${SOURCE}

clean:
	rm -rf *~ ${TARGET}